### ISSUE TITLE
Identify keyframes for consumers

### ISSUE THREAD

**Issue by sax** [membraneframework/membrane_rtp_vp8_plugin#8]
My team is creating a membrane element that receives the buffer output of this plugin, and it would be really useful to identify keyframes. This might also be generally useful in terms of handling `NACK` packet loss indicators, potentially having the RTP plugin save off keyframes for retransmission.

I was looking at the [RFC](https://datatracker.ietf.org/doc/html/rfc7741) for the ability to quickly identify keyframes in an element that receives this buffer output, and thought that it might be a useful addition to this plugin.

My understanding of this plugin is that it accumulates packets until whole frames (keyframes or interframes) are received, then passes them on to consumers. So if a keyframe is by the sender across multiple packets, this plugin will combine them.

The VP8 RFC includes [this chunk](https://www.rfc-editor.org/rfc/rfc6386#section-19.1) about identifying keyframes:

```
   | Frame Tag                                         | Type  |
   | ------------------------------------------------- | ----- |
   | frame_tag                                         | f(24) |
   | if (key_frame) {                                  |       |
   |     start_code                                    | f(24) |
   |     horizontal_size_code                          | f(16) |
   |     vertical_size_code                            | f(16) |
   | }                                                 |       |

   The 3-byte frame tag can be parsed as follows:

   ---- Begin code block --------------------------------------

   unsigned char *c = pbi->source;
   unsigned int tmp;

   tmp = (c[2] << 16) | (c[1] << 8) | c[0];

   key_frame = tmp & 0x1;
   version = (tmp >> 1) & 0x7;
   show_frame = (tmp >> 4) & 0x1;
   first_part_size = (tmp >> 5) & 0x7FFFF;

   ---- End code block ----------------------------------------
```

I haven't been able to map that back into this plugin yet.

**Comment by mickel8** [comment]
Hi @sax,
I know this is very old issue and I assume you don't need it anymore but we have added [is_keyframe](https://hexdocs.pm/membrane_rtp_vp8_plugin/Membrane.RTP.VP8.Utils.html#is_keyframe/1) function
